Name = "Cutscene Trigger"
Category = "SWITCH"
Version = 1
Notes = "Starts a cutscene if Set Flag is not set and Get Flag is either set or its NULL. If distance is not set to 0 then it only starts when Link is inside the specified area. Force will ignore any ongoing cutscenes. Flip Get makes the cutscene run when the Get Flag is not set. The cutscene is played from the header specified by header index."

[[Property]]
	Mask          = 0xFF00
	Name          = "Set Flag"
	Target        = "XRot"
	Dropdown = [ [ 0xFF, "NULL"] ]
[[Property]]
	Mask           = 0x00FF
	Name           = "Get Flag"
	Target         = "XRot"
	Dropdown = [ [ 0xFF, "NULL"] ]
[[Property]]
	Mask          = 0xC000
	Name          = "Set Flag Type"
	Target        = "Var"
	Dropdown = [
		[ 0, "Switch"      ],
		[ 1, "Chest"       ],
		[ 2, "Collectible" ],
		[ 3, "Global"      ],
	]
[[Property]]
	Mask          = 0x3000
	Name          = "Get Flag Type"
	Target        = "Var"
	Dropdown = [
		[ 0, "Switch"      ],
		[ 1, "Chest"       ],
		[ 2, "Collectible" ],
		[ 3, "Global"      ],
	]
[[Property]]
	Mask          = 0xFF00
	Name          = "Flip Get"
	Target        = "YRot"
	Dropdown = [ [ 0, "false"], [ 1, "true" ] ]
[[Property]]
	Mask          = 0x0C00
	Name          = "Force"
	Target        = "Var"
	Dropdown = [ [ 0, "false"], [ 1, "true" ] ]
[[Property]]
	Mask          = 0x03FF
	Name          = "Distance (x10)"
	Target        = "Var"
	Decimal       = true
[[Property]]
	Mask          = 0xF0
	Name          = "Distance Type"
	Target        = "YRot"
	Dropdown = [
		[ 0, "XZ" ],
		[ 1, "XZY" ],
	]
[[Property]]
	Mask          = 0xF
	Name          = "Header Index"
	Target        = "YRot"
	